### ISSUE TITLE
`pac package deploy` times out when upgrade detected

### ISSUE THREAD

**Issue by filcole** [microsoft/powerplatform-vscode#189]
When an existing solution need to be upgraded `pac package deploy` is timing out, e.g.

`pac package deploy -p .\PackageDeploy.dll --logFile installog2.txt --logConsole`

Gives the following logs.

Are there any timeout or config settings that can be used to tune?  This [tip](https://www.develop1.net/public/post/2021/05/19/increase-timeout-for-pac-pcf-push) from @ScottDurow doesn't seem to work.

Thanks! 

```
PackageDeployVerb Information: 8 : Message: ************** Solution IMPORT *****************
PackageDeployVerb Information: 8 : Message: Starting Processing Of Solution: My Amazing Solution(MyAmazingSolution), Version: 1.0.0.1, PackageVersion: 9.2
Beginning load of solution My Amazing Solution, version: 1.0.0.1.
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=OverrideSolutionImportDecision : Status=Execute
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=OverrideSolutionImportDecision : Status=Complete : Duration=00:00:00.0002229
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Processing Solution - Inbound version: 1.0.0.1 - Deployed Version 1.0.0.0, System Determined Import Action: Import
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - ImportSolution - Overwrite solution version My Amazing Solution with version 1.0.0.1
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Updating solution Version: 1.0.0.0 to Version : 1.0.0.1 - Importing Holding Solution - USING 7.2+ API
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=PreSolutionImport : Status=Execute
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=PreSolutionImport : Status=Complete : Duration=00:00:00.0002173
PackageDeployVerb Information: 8 : Message: ImportSolution - Async Supported = True
PackageDeployVerb Information: 8 : Message: DeleteAndPromote - Async Supported = True
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Executing Solution Import - UploadHoldingSolutionV2
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Fetching Data
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Import Progress is : 100
PackageDeployVerb Information: 8 : Message: MyAmazingSolution Solution Import Result = success - Duration: 00:01:16.9528092
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Updated solution Version: 1.0.0.0 to Version : 1.0.0.1
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=RunSolutionUpgradeMigrationStep : Status=Execute
PackageDeployVerb Information: 8 : Message: MyAmazingSolution : User Code Execution : OP=RunSolutionUpgradeMigrationStep : Status=Complete : Duration=00:00:00.0003294
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Updating solution Version: 1.0.0.0 to Version : 1.0.0.1 - Deleting Holding Solution
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Executing Solution Import - PromoteHoldingSolutionV2
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ************ TimeoutException - DeleteAndPromote : Delete and Promote Solution to New version(DeleteAndPromoteSolutionRequest) |=> The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
Source  : mscorlib
Method  : HandleReturnMessage
Date    : 17/04/2022
Time    : 19:19:09
Error   : The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
Stack Trace     : Server stack trace:
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1 :
Source  : System.ServiceModel
Method  : ProcessGetResponseWebException
Date    : 17/04/2022
Time    : 19:19:09
Error   : The HTTP request to 'https://ipc-qa.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
Stack Trace     : at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
======================================================================================================================
Inner Exception Level 2 :
Source  : System
Method  : GetResponse
Date    : 17/04/2022
Time    : 19:19:09
Error   : The operation has timed out
Stack Trace     : at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
======================================================================================================================

[... snip ...]

PackageDeployVerb Error: 2 : Message: MyAmazingSolution - Updating solution Version: 1.0.0.0 to Version : 1.0.0.1 - Deleting Holding Solution FAILED :  : ************ TimeoutException - DeleteAndPromote : Delete and Promote Solution to New version(DeleteAndPromoteSolutionRequest) |=> The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. => The HTTP request to 'https://myenv.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout. => The operation has timed out[TerminalFailure] Failed to Execute Command - DeleteAndPromote : RequestID=ba768f36-0371-4c6e-b27c-678c8b0b675e : Delete and Promote Solution to New version(DeleteAndPromoteSolutionRequest) duration=00:02:00.0918443 ExceptionMessage = The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout. => The HTTP request to 'https://myenv.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout. => The operation has timed out
Source  : mscorlib
Method  : HandleReturnMessage
Date    : 19:19:09
Time    : 17/04/2022
Error   : The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
Stack Trace     : Server stack trace:
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1 :
Source  : System.ServiceModel
Method  : ProcessGetResponseWebException
Date    : 19:19:09
Time    : 17/04/2022
Error   : The HTTP request to 'https://myenv.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
Stack Trace     : at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
======================================================================================================================
Inner Exception Level 2 :
Source  : System
Method  : GetResponse
Date    : 19:19:09
Time    : 17/04/2022
Error   : The operation has timed out
Stack Trace     : at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
======================================================================================================================
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorCode  - -2146233083
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorName  - NotProvided
PackageDeployVerb Information: 8 : Message: errorDetails - Message  - The request channel timed out while waiting for a reply after 00:01:59.9819968. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
PackageDeployVerb Information: 8 : Message: errorDetails - Type  - Application
PackageDeployVerb Information: 8 : Message: errorDetails - StatusCode  - 500
PackageDeployVerb Information: 8 : Message: errorDetails - Source  - PackageDeployer
PackageDeployVerb Information: 8 : Message: errorDetails - TraceText  - ......Server stack trace: ......   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)......   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)......   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)......   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)......   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)............Exception rethrown at [0]: ......   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)......   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)......   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)......   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)......   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorCode  - -2146233083
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorName  - NotProvided
PackageDeployVerb Information: 8 : Message: errorDetails - Message  - The HTTP request to 'https://myenv.crm11.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
PackageDeployVerb Information: 8 : Message: errorDetails - Type  - Application
PackageDeployVerb Information: 8 : Message: errorDetails - StatusCode  - 500
PackageDeployVerb Information: 8 : Message: errorDetails - Source  - PackageDeployer
PackageDeployVerb Information: 8 : Message: errorDetails - TraceText  -    at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)......   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)......   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorCode  - -2146233079
PackageDeployVerb Information: 8 : Message: errorDetails - ErrorName  - NotProvided
PackageDeployVerb Information: 8 : Message: errorDetails - Message  - The operation has timed out
PackageDeployVerb Information: 8 : Message: errorDetails - Type  - Application
PackageDeployVerb Information: 8 : Message: errorDetails - StatusCode  - 500
PackageDeployVerb Information: 8 : Message: errorDetails - Source  - PackageDeployer
PackageDeployVerb Information: 8 : Message: errorDetails - TraceText  -    at System.Net.HttpWebRequest.GetResponse()......   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
PackageDeployVerb Information: 8 : Message: RaiseFailEvent - update progress with fail event
PackageDeployVerb Information: 8 : Message: ************** BEGIN Queuing UpdateRibbonClientMetadata Job *****************
Beginning queueing up UpdateRibbonClientMetadata job.
PackageDeployVerb Information: 8 : Message: Trying to queue up UpdateRibbonClientMetadata Job.
PackageDeployVerb Information: 8 : Message: Time taken for queuing the ribbon job: 00:00:00.3296308
PackageDeployVerb Information: 8 : Message: ************** UpdateRibbonClientMetadata Job QUEUED *****************
PackageDeployVerb Information: 8 : Message: ****** PACKAGE DEPLOYMENT PROCESS COMPLETED. Result:FAILED  Duration:00:03:19.9664819 ******
PackageDeployVerb Information: 8 : Message: MyAmazingSolution - Pausing for 5 seconds before resuming operation. Retry# 0
Microsoft PowerPlatform CLI
Version: 1.14.2+g7205df7

Error: Updating solution My Amazing Solution version 1.0.0.0 to version 1.0.0.1: Deleting Holding solution.

Usage: pac package deploy [--logFile] [--logConsole] --package

  --logFile                   Log file path (alias: -lf)
  --logConsole                Output log to console (alias: -c)
  --package                   path to a package dll or zip file with a package (alias: -p)
```

**Comment by davidjenni** [comment]
@filcole the package deployment fails due to the client timeout when the PackageDeployer code library calls DeleteAndPromote. Unfortunately, today, this request is only available as synchronous call to Dataverse, which assumes the synch response to return before the 2-4 min http idle timeout. 

The majority of pac CLI is using the newer Dataverse Service Client lib, which has a default MaxConnectionTimeout of 4 min already, but for pac package deploy, we're dependent on the PackageDeployer core library, which is still on the older CrmServiceClient library. It has a default maxConnTimeout of 2 min, which corresponds with the timeout error you experienced.
I'm adding a bug on our end to ensure that both client libraries use the same 4 min default.
AB#2683003

Here's a tentative workaround/mitigation:
edit the pac.exe.config that is located next to where you launch the pac.exe from (if in doubt, call `where pac.exe` in cmd or `gcm pac.exe` in PS/PSCore)
To try to override the default 2 min for CrmSvcClient, add the following to the <appSettings> section:
Note that setting the timeout to longer than 4min will usually NOT help, since the edge proxies of our Dataverse endpoints enforce the common ~4 min idle http connection timeout.

```
  <appSettings>
    <add key="MaxCrmConnectionTimeOutMinutes" value="4" />
  </appSettings>
</configuration>

```

**Comment by filcole** [comment]
Thanks for the info @davidjenni. We have solutions that take a *long* time (multiple hours) to upgrade.  I think from what you're saying it will still timeout after 4 minutes when trying to do a DeleteAndPromote.  

Looking at the SDK I can't see anyway to control if DeleteAndPromote is called, versus separate Import and Apply.  https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.packagedeployment.crmpackageextentionbase.importextension.overridesolutionimportdecision?view=dataverse-sdk-latest

So looks like best to use `pac solution import --import-as-holding --async` and then `pac solution upgrade --async` ?

**Comment by davidjenni** [comment]
@filcole yes, that would work as mitigation for now, since both of those operations are indeed asynchronous. But you'd have to discard the additional steps package deployer (via pac package deploy) does; I assume your current scenario doesn't need e.g. custom code and/or data import right now.

I got clarification that the DeleteAndPromote is indeed only available as a synchronous operation in Dataverse, so if it takes more than 4 min (with the increased client timeout), your package deploy is still prone to fail.
There is work planned on the Dataverse side to offer DeleteAndPromote as an asynchronous ops as well, but no ETA for now.

**Comment by filcole** [comment]
Hi @davidjenni.  Thanks for the reply.  I was really hoping to take advantage of package deployer with multiple solutions, plus data, plus logic to determine whether to Update (fast) or Upgrade (slow) solutions.

**Comment by MattB-msft** [comment]
@filcole ,  
as @davidjenni  mentioned here:

> Here's a tentative workaround/mitigation:
edit the pac.exe.config that is located next to where you launch the pac.exe from (if in doubt, call where pac.exe in cmd or gcm pac.exe in PS/PSCore)

Add these 2 settings:

```xml
  <appSettings>
    <add key="UseAsyncForSolutionDeleteAndPromote" value="True" />
    <add key="UseAsyncForSolutionImport" value="True" />
  </appSettings>
```

This will tell the PD system to use Async for SolutionImport and Deleteandpromote by default.  You can also override it in the package definition itself as well. 

to do that,  in the Inputconfig.xml file in your package, you add **requiredimportmode="async"** to your solution reference. 
That will ask PD to attempt to use Async if available on the target environment. 

for example: 

```xml
<solutions>
    <configsolutionfile solutionpackagefilename="foo_1_0_0_0_managed.zip" overwriteunmanagedcustomizations="false" publishworkflowsandactivateplugins="true" missingdependencybehavior="fault" requiredimportmode="async"  />
  </solutions>
```

**Comment by davidjenni** [comment]
@filcole the August refresh for pac CLI will initialize the PackageDeployer API to use async operations for solution import and deleteAndPromote, if those are enabled on the target environment. ETA: mid October
