### ISSUE TITLE
pac solution add-reference w/ .pcfproj - System.IO.IOException: The tag present in the reparse point buffer is invalid.

### ISSUE THREAD

**Issue by davidjenni** [microsoft/powerplatform-vscode#316]
reported via nuget gallery by Moohammed:

The new version of PowerApps CLI has a bug when we are trying to run "pac add reference". Here's the error details from pac log file:

2022-10-16 17:05:03.8402|INFO|bolt.cli.CommandProcessor|StartExecutingVerb (Verbs: ["solution","add-reference"])
2022-10-16 17:05:03.8402|INFO|bolt.cli.Verb|Processing 'add-reference' verb arguments 2022-10-16 17:05:03.8562|INFO|bolt.cli.Verb|Executing 'add-reference' verb 
2022-10-16 17:05:03.9972|INFO|bolt.cli.CommandProcessor|EndExecutingVerb (Success: False, Execution Time(ms): 145) 
2022-10-16 17:05:04.0192|FATAL|bolt.cli.Session|The tag present in the reparse point buffer is invalid. 

EXCEPTION: System.IO.IOException: The tag present in the reparse point buffer is invalid.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator1.AddSearchableDirsToStack(SearchData localSearchData)
at System.IO.FileSystemEnumerableIterator1.MoveNext() at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source)
at bolt.module.solution.references.PcfReferenceHandler.GetLocalFileInfo(String searchDirectory, String searchPattern)
at bolt.module.solution.references.PcfReferenceHandler.FetchPcfComponent(String filePath)
at bolt.module.solution.references.ProjectReferenceHandler.FetchComponents(String cdsProjFilePath)
at bolt.module.solution.verbs.SolutionAddReferenceVerb.Execute(IContext context, Command command)
at bolt.cli.Verb.&lt;&gt;c__DisplayClass8_0.&lt;&lt;RunVerbExecutor&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at bolt.cli.Verb.RunVerbExecutor(IProcessCommandContext context, Command command)
at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue1 nextCommands)
at bolt.cli.CommandProcessor.ProcessCommands(Queue1 commands, IVerbFactory factory)
at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)
at bolt.cli.Session.Run(ProgramArguments args) 2022-10-16 17:05:04.0242|ERROR|bolt.cli.Session|
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileSystemEnumerableIterator1.AddSearchableDirsToStack(SearchData localSearchData)
at System.IO.FileSystemEnumerableIterator1.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source) at bolt.module.solution.references.PcfReferenceHandler.GetLocalFileInfo(String searchDirectory, String searchPattern)
at bolt.module.solution.references.PcfReferenceHandler.FetchPcfComponent(String filePath) at bolt.module.solution.references.ProjectReferenceHandler.FetchComponents(String cdsProjFilePath)
at bolt.module.solution.verbs.SolutionAddReferenceVerb.Execute(IContext context, Command command)
at bolt.cli.Verb.<>c__DisplayClass8_0.<<RunVerbExecutor>b__0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

tracked as QFE candidate: AB#2984636

**Comment by davidjenni** [comment]
should be fixed in pac CLI 1.20.x
