### ISSUE TITLE
Error on Pac Init - Cannot locate the strings.localized.json resource file for the culture en-US

### ISSUE THREAD

**Issue by benlaughlin** [microsoft/powerplatform-vscode#453]
I am trying to build a Power Apps Component.

I am running a M1 Mac with VS Code. I have installed the Power Platform Tools plug-in.

I am following the tutorial here: https://learn.microsoft.com/en-us/power-apps/developer/component-framework/implementing-controls-using-typescript

When I run the pcf init command:
```
pac pcf init --namespace SampleNamespace --name LinearInputControl --template field --run-npm-install
```

I get the following error:

```
Unhandled exception. System.ApplicationException: Internal: Cannot locate the strings.localized.json resource file for the culture en-US. Was looking in /Users/ben/Library/Application Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac/tools/loc/en/strings.localized.json.
   at bolt.system.LocalizedStrings`1.LazyInit()
   at bolt.system.LocalizedStrings`1.GetStringResource(TLocStringEnum locString)
   at bolt.system.LocalizedStrings`1.GetString(TLocStringEnum locString, Int32 argumentCount, Func`2 formatter)
   at bolt.system.LocalizedStrings`1.GetString_0(TLocStringEnum locString)
   at bolt.cli.Session.<>c.<ConfigureServices>b__14_6(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at bolt.cli.Session.CreateFeatureFlagsSingleton(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at bolt.cli.Session.CreateOutputWindow(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at bolt.cli.Session.Run(ProgramArguments args)
   at bolt.Program.Main()
zsh: abort      pac pcf init --namespace SampleNamespace --name LinearInputControl --template
```

After investigating, I can see there is no English language file at the location: /Users/ben/Library/Application Support/Code/User/globalStorage/microsoft-isvexptools.powerplatform-vscode/pac/tools/loc/en/strings.localized.json

If I take one of the other language files and copy it to the .../en/srings.localized.json location everything works all that way through to building the solution package. My issue is however, everything is in another language.

Is the an English strings.localized.json file I can drop in to fix?

**Comment by tehcrashxor** [comment]
I haven't been able to repro on my M1 mac mini, with either v1.1.16 (version at the time this issue was opened) nor any more recent versions.  In every case, the english /loc/ files have existed where we expected.

@benlaughlin, are you still able to reproduce?

**Comment by benlaughlin** [comment]
Thanks @tehcrashxor , it is still an issue for me. 

Is it possible to send a repo link to the English file, perhaps I can copy it over myself to try? 

My locale is en_AU by the way. Perhaps that is a factor for replicating it.

**Comment by tehcrashxor** [comment]
The PAC CLI is not yet open source, so I don't have a repo link for the file.  
However, the files are present in the PAC Nuget packages, so they can be found by just unzipping the .nuget file, and grabbing them from the `tools/loc/*` directory.

Windows: [Microsoft.PowerApps.CLI](https://www.nuget.org/packages/Microsoft.PowerApps.CLI)
MacOS: [Microsoft.PowerApps.CLI.Core.osx-x64](https://www.nuget.org/packages/Microsoft.PowerApps.CLI.Core.osx-x64)
Linux: [Microsoft.PowerApps.CLI.Core.linux-x64](https://www.nuget.org/packages/Microsoft.PowerApps.CLI.Core.linux-x64)

This VS Code extension "installs" PAC by just unzipping the nuget file into the extension's storage directory [here in `installCli(...) of CliAcquisition.ts ](https://github.com/microsoft/powerplatform-vscode/blob/e2bd756d124cf2f201726b209991dd2c11236128/src/client/lib/CliAcquisition.ts#L78), so it's definitely strange that the loc files are missing when `pac` itself is successfully unzipped.

I wouldn't expect `en-AU` to affect anything, as the .net localization should find `en` when no more specific `en-*` is found.
