### ISSUE TITLE
Error: System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.Messages.DeleteRequest' to type 'Microsoft.Xrm.Sdk.Messages.UpsertRequest'.

### ISSUE THREAD

**Issue by danielvanderuit** [microsoft/powerplatform-vscode#950]
Hi all,

Since a few days now, we have been having issues with the `pac powerpages upload` command. Quite late in the process, the following error occurs:

```
2024-05-15 09:03:23.3524 | ERR | bolt.module.paportal.PortalDataImporter :: PAPortalUploadAction(): Failed
2024-05-15 09:03:23.4149 | ERR | bolt.module.paportal.PortalDataImporter :: System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Sdk.Messages.DeleteRequest' to type 'Microsoft.Xrm.Sdk.Messages.UpsertRequest'.
   at bolt.module.paportal.PortalDataImporter.<>c__DisplayClass31_0.<ExecuteRequestsAndHandleResponse>b__0(OrganizationRequestCollection requests)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
```

I am attaching the log file, hopefully that helps.
[pac-log.txt](https://github.com/microsoft/powerplatform-vscode/files/15320710/pac-log.txt)

I do not recall anything being changed on our end that could cause this. Also, we see this happening for multiple projects.

Looking forward to your replies! If more info is required, feel free to reach out.

**Comment by danielvanderuit** [comment]
Update: Fixed by downgrading to an earlier version (1.31.6 in my case).
